tone_options = [
    "Formal",
    "Informal",
    "Optimistic",
    "Worried",
    "Friendly",
    "Curious",
    "Assertive",
    "Encouraging",
    "Surprised",
    "Cooperative",
]

# Country Options
country_options = [
    "ae",
    "ar",
    "at",
    "au",
    "be",
    "bg",
    "br",
    "ca",
    "ch",
    "cn",
    "co",
    "cu",
    "cz",
    "de",
    "eg",
    "fr",
    "gb",
    "gr",
    "hk",
    "hu",
    "id",
    "ie",
    "il",
    "in",
    "it",
    "jp",
    "kr",
    "lt",
    "lv",
    "ma",
    "mx",
    "my",
    "ng",
    "nl",
    "no",
    "nz",
    "ph",
    "pl",
    "pt",
    "ro",
    "rs",
    "ru",
    "sa",
    "se",
    "sg",
    "si",
    "sk",
    "th",
    "tr",
    "tw",
    "ua",
    "us",
    "ve",
    "za",
    "all",
]
language_options = [
    "ar",
    "de",
    "en",
    "es",
    "fr",
    "he",
    "it",
    "nl",
    "no",
    "pt",
    "ru",
    "se",
    "ud",
    "zh",
    "all",
]
category_options_newsapi = [
    "business",
    "entertainment",
    "general",
    "health",
    "science",
    "sports",
    "technology",
    "all",
]

category_options_newsdataio = [
    None,
    "Business",
    "Crime",
    "Domestic",
    "Education",
    "Entertainment",
    "Environment",
    "Food",
    "Health",
    "Other",
    "Politics",
    "Science",
    "Sports",
    "Technology",
    "Top",
    "Tourism",
    "World",
]

image_model_options = ["dall-e-3","dall-e-2"]

image_size_option = ["1024x1024", "1024x1792", "1792x1024"]

image_styles_options = [
    None,
    "Abstract Art",
    "Realistic Scenes",
    "Fantasy Worlds",
    "Portraits",
    "Architectural Designs",
    "Conceptual Illustrations",
    "Cartoons and Comics",
    "Anime",
    "Scientific Diagrams",
    "Product Designs",
    "Nature and Wildlife",
    "Food and Culinary Creations",
    "Historical Scenes",
    "Sci-Fi and Futuristic Art",
    "Surreal and Dreamlike",
    "Steampunk",
    "Minimalist Art",
    "Pop Art",
    "Vintage and Retro",
    "Horror and Dark Art",
    "Whimsical and Playful",
]

audience_type_options = ["General", "Knowledgeable", "Expert", "5 Year Old"]

content_structure_options = {
    "": None,
    "News Report": "Follow a traditional news article structure, presenting the who, what, when, where, and why of a story.",
    "Storytelling/Narrative": "Tell a story related to the topic, engaging readers emotionally and contextually.",
    "Listicle": "Present information in a list format, making it easy for readers to consume key points.",
    "Explainer Article": "Break down complex concepts or processes into simpler, easily understandable parts.",
    "How-to Guide": "Structure the content as a step-by-step guide, providing practical instructions on a particular topic.",
    "Q&A Format": "Frame the content in a question-and-answer format, addressing common queries or concerns.",
    "Opinion Piece": "Craft the content as an opinion piece, allowing for a more subjective and expressive writing style.",
    "Comparison/Contrast": "Compare and contrast different aspects or options related to the topic.",
    "Interview Transcript": "Structure the content as a transcript of an interview, incorporating dialogue and perspectives.",
    "Review": "Evaluate and critique a product, service, or topic, providing insights and recommendations.",
    "Educational Guide": "Create an educational piece that imparts knowledge on a specific subject in a structured manner.",
    "Profile/Feature Article": "Highlight a person, organization, or event, providing a detailed profile or feature.",
    "Debate Format": "Present different perspectives on an issue, encouraging critical thinking and discussion.",
    "Personal Reflection": "Share personal experiences or reflections related to the topic.",
    "Humorous/Satirical Piece": "Infuse humor or satire into the content to entertain and engage the audience.",
    "Case Study": "Present in-depth analyses of real-world examples or scenarios related to the topic.",
    "Timeline": "Present information chronologically, especially useful for historical or evolving topics.",
    "Technical Documentation": "Structure the content with a focus on technical details, suitable for more specialized or professional audiences.",
}

social_platform_options = [
    None,
    "Instagram",
    "Twitter",
    "Facebook",
    "LinkedIn",
    "Reddit",
    "WhatsApp",
    "Medium",
    "Quora",
]
